(()=>{
const $=id=>document.getElementById(id), KEY='daxiaCoachV4', LEGACY='daxiaCoachOnlineV1', MAX_MS=30*60*1000, BG_PAUSE_MS=90*1000;
const EX={
 squat:{name:'深蹲',type:'reps',min:8,max:12,load:'sq',unit:'kg总负重',rest:70,inc:1,cue:'臀部向后下坐，膝盖跟随脚尖，脚掌稳稳踩地。'},
 rdl:{name:'罗马尼亚硬拉 RDL',type:'reps',min:8,max:12,load:'rdl',unit:'kg总负重',rest:80,inc:1,cue:'膝微屈，臀部向后推，背部中立，感受臀腿后侧拉长。'},
 push:{name:'俯卧撑',type:'reps',min:8,max:15,load:null,unit:'自重',rest:60,cue:'头背臀保持一条直线，肘部约45°，不要塌腰。'},
 row:{name:'划船',type:'reps',min:8,max:12,load:'rowLoad',unit:'kg/手',rest:60,inc:.5,cue:'稳住肩胛，把肘部向后拉，顶端短暂停顿。'},
 pull:{name:'下拉 / 引体',type:'reps',min:6,max:12,load:null,unit:'自重/弹力带',rest:70,cue:'胸口微抬，把肘部向身体两侧下拉，感受背部收紧。'},
 carry:{name:'农夫行走',type:'time',seconds:35,maxSeconds:45,load:'carry',unit:'kg/手',rest:55,inc:.5,cue:'站直、核心收紧、肩膀自然下沉，稳定缓慢地走。'}
};
const VARIANTS={
 squat:{chair:{name:'椅子坐站',min:8,max:12,load:null,unit:'徒手 / 稳固椅子',cue:'缓慢坐向椅面，轻触后站起。膝盖跟随脚尖，起身时脚掌稳稳踩地。'},bodyweight:{name:'徒手深蹲',min:10,max:15,load:'sq',unit:'kg总负重',cue:'臀部向后下坐，膝盖跟随脚尖，脚掌稳稳踩地；只做到能保持躯干稳定的深度。'}},
 push:{wall:{name:'墙面俯卧撑',min:12,max:20,load:null,unit:'墙面',cue:'身体保持一条直线，胸口靠近墙面，再平稳推回；不要只动头和肩。'},inclineHigh:{name:'高台俯卧撑',min:8,max:15,load:null,unit:'厨房台 / 高桌',cue:'双手撑稳高台，头背臀保持一条直线，胸口主动靠近支撑面。'},inclineLow:{name:'低台俯卧撑',min:6,max:12,load:null,unit:'稳固桌沿',cue:'支撑面必须稳固不滑动。全程收紧躯干，肘部约45°，不要塌腰。'},standard:{name:'标准俯卧撑',min:5,max:12,load:null,unit:'自重',cue:'头背臀保持一条直线，肘部约45°，胸口主动靠近地面，不要塌腰或耸肩。'}},
 pull:{band:{name:'弹力带下拉',min:8,max:12,load:null,unit:'长弹力带',cue:'固定点必须可靠。胸口微抬，把肘部向身体两侧下拉，感受背部收紧。'},assisted:{name:'辅助引体',min:5,max:10,load:null,unit:'单杠 + 可靠辅助',cue:'先让肩胛稳定，再把肘部向下拉。辅助只用来减少难度，不要借力甩动。'},pullup:{name:'引体向上',min:3,max:8,load:null,unit:'稳固单杠',cue:'从稳定悬垂开始，先收紧肩胛，再把胸口向杠靠近；不要摆腿借力。'},rowSub:{name:'第二种划船（替代垂直拉）',min:8,max:12,load:null,unit:'背包 / 弹力带',cue:'没有安全的垂直拉器械时，用另一种划船补足拉力训练；动作慢、顶端停顿。'}},
 row:{dumbbell:{name:'单臂划船',min:8,max:12,load:'rowLoad',unit:'kg/手',cue:'躯干稳定，把肘部向后拉，顶端短暂停顿；不要用身体甩起重量。'},band:{name:'弹力带划船',min:8,max:15,load:null,unit:'弹力带阻力',cue:'固定点必须可靠。先稳定肩胛，再把手柄拉向身体，顶端短暂停顿。'}}
};
const LADDERS={squat:['chair','bodyweight'],push:['wall','inclineHigh','inclineLow','standard']};
const DEFAULT_PROFILE={calibrated:false,squat:'bodyweight',push:'inclineHigh',pull:'band',row:'dumbbell'};
const PLAN={A:{type:'正常日 A',ids:['squat','push','row','carry'],sets:2},B:{type:'正常日 B',ids:['rdl','pull','push','carry'],sets:2},LIGHT:{type:'轻量日',ids:['squat','rdl','row','pull'],sets:1,light:true},RECOVERY:{type:'恢复日',ids:['squat','push','row','carry'],sets:1,recovery:true}};
const fresh=()=>({version:3,voice:true,loads:{sq:0,rdl:0,rowLoad:0,carry:0},targets:{},history:[],profile:{...DEFAULT_PROFILE},active:null});
function load(){let s;try{s=JSON.parse(localStorage.getItem(KEY))}catch(e){}const existed=!!s;if(!s)s=fresh();s.version=3;s.loads=Object.assign({sq:0,rdl:0,rowLoad:0,carry:0},s.loads||{});s.targets=s.targets||{};s.history=Array.isArray(s.history)?s.history:[];s.profile=Object.assign({},DEFAULT_PROFILE,s.profile||{});if(existed&&(!s.profile||typeof s.profile.calibrated!=='boolean'))s.profile={...DEFAULT_PROFILE};if(!localStorage.getItem(KEY)){try{let o=JSON.parse(localStorage.getItem(LEGACY)||'null');if(o&&o.loads){s.loads.sq=Number(o.loads.sq||0);s.loads.rdl=Number(o.loads.rdl||0);s.loads.rowLoad=Number(o.loads.row||0);s.loads.carry=Number(o.loads.carry||0)}if(o&&Array.isArray(o.sessions))o.sessions.forEach(x=>s.history.push({date:x.date,type:'V3',partial:false,rating:x.rating||null,source:'v3'}))}catch(e){}}if(!s.profile.calibrated)s.active=null;return s}
let st=load();
function save(){localStorage.setItem(KEY,JSON.stringify(st))}
function dateKey(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function fmtDate(){let d=new Date();return `${d.getMonth()+1}月${d.getDate()}日 · 星期${'日一二三四五六'[d.getDay()]}`}
function yday(){let d=new Date();d.setDate(d.getDate()-1);return dateKey(d)}
function meta(id){let e=EX[id],v=VARIANTS[id];if(!v)return e;let key=st.profile[id],m=v[key]||Object.values(v)[0];return Object.assign({},e,m)}
function target(id){let e=meta(id),t=st.targets[id];if(!t){t={reps:e.type==='reps'?e.min:null,seconds:e.type==='time'?e.seconds:null,success:0,misses:0};st.targets[id]=t}if(e.type==='reps')t.reps=Math.max(e.min,Math.min(Number(t.reps||e.min),e.max));return t}
function choosePlan(){let h=st.history.filter(x=>x.date!==dateKey()).slice(-6),last=h[h.length-1];if(last&&last.date===yday()&&last.rating==='hard')return PLAN.RECOVERY;let consec=0,cur=new Date();for(let i=1;i<=6;i++){let d=new Date(cur);d.setDate(cur.getDate()-i);if(h.some(x=>x.date===dateKey(d)))consec++;else break}if(consec>=2)return PLAN.LIGHT;let normals=[...h].reverse().find(x=>x.planKey==='A'||x.planKey==='B');return normals&&normals.planKey==='A'?PLAN.B:PLAN.A}
function planKey(p){return p===PLAN.A?'A':p===PLAN.B?'B':p===PLAN.LIGHT?'LIGHT':'RECOVERY'}
function buildPlan(){let p=choosePlan(),arr=[];p.ids.forEach(id=>{for(let i=1;i<=p.sets;i++)arr.push({id,set:i,total:p.sets,result:null})});return{type:p.type,planKey:planKey(p),light:!!p.light,recovery:!!p.recovery,arr}}
let plan,pos=-1,mode='ready',warm=120,restSec=0,timer=null,deadline=0,sessionMs=0,lastTick=0,hiddenAt=0,sessionFinished=false;
function restoreOrBuild(){let a=st.active;if(st.profile.calibrated&&a&&a.date===dateKey()&&a.plan&&Array.isArray(a.plan.arr)){plan=a.plan;pos=a.pos??-1;mode=a.mode||'ready';warm=a.warm??120;restSec=a.restSec||0;sessionMs=a.sessionMs||0;if(mode==='done'){st.active=null;plan=buildPlan();pos=-1;mode='ready';warm=120;sessionMs=0}}else plan=buildPlan()}
restoreOrBuild();
function persist(){if(!st.profile.calibrated||mode==='done'||sessionFinished)st.active=null;else st.active={date:dateKey(),plan,pos,mode,warm,restSec,sessionMs,updated:Date.now()};save()}
function speak(t){if(!st.voice||!('speechSynthesis'in window))return;try{speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='zh-CN';u.rate=1.02;speechSynthesis.speak(u)}catch(e){}}
function loadText(id){let e=meta(id);if(!e.load)return e.unit||'自重';let v=Number(st.loads[e.load]||0);return v>0?`${v} ${e.unit}`:'暂不负重'}
function prescribed(id){let e=meta(id),t=target(id);if(e.type==='time'){let sec=t.seconds||e.seconds;if(plan.light||plan.recovery)sec=Math.max(25,sec-10);return{text:`${sec}秒`,value:sec}}let reps=t.reps||e.min;if(plan.light)reps=Math.max(e.min,Math.min(reps-2,e.max));if(plan.recovery)reps=Math.max(e.min,Math.min(reps-3,e.max));return{text:`${reps}次`,value:reps}}
function estimated(){let sec=120;plan.arr.forEach(x=>{let e=meta(x.id);sec+=(e.type==='time'?prescribed(x.id).value:35)+e.rest});return Math.min(30,Math.max(8,Math.ceil(sec/60)))}
function fmtElapsed(){let n=Math.floor(sessionMs/1000),m=Math.floor(n/60),s=n%60;return `${m}:${String(s).padStart(2,'0')}`}
function completedCount(){return plan.arr.filter(x=>x.result!==null).length}
function renderPlan(){let box=$('plan');box.innerHTML='';plan.arr.forEach((x,i)=>{let e=meta(x.id),d=document.createElement('div');d.className='item'+(i===pos?' active':'')+(x.result!==null?' done':'');let mark=x.result==='hit'?'✓':x.result==='miss'?'·':x.result==='skip'?'—':i+1;d.innerHTML=`<div class="num">${mark}</div><div><b>${e.name}</b><div class="mini">第${x.set}/${x.total}组 · ${loadText(x.id)}</div></div><div class="goal">${prescribed(x.id).text}</div>`;box.appendChild(d)});$('progress').textContent=`${completedCount()} / ${plan.arr.length}组`;$('eta').innerHTML=`预计约${estimated()}分钟 · <span class="cap">硬上限30分钟</span>`;$('dayType').textContent=st.profile.calibrated?plan.type:'待校准'}
function renderHistory(){let box=$('history');box.innerHTML='';for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let k=dateKey(d),h=[...st.history].reverse().find(x=>x.date===k),wrap=document.createElement('div');wrap.className='day';let dot=document.createElement('div');dot.className='dot'+(h?(h.partial?' partial':' ok'):'');dot.textContent=h?(h.partial?'◐':'✓'):'·';let lab=document.createElement('div');lab.textContent='日一二三四五六'[d.getDay()];wrap.append(dot,lab);box.appendChild(wrap)}}
function syncCalibration(){['squat','push','pull','row'].forEach(id=>{let el=$('cal'+id[0].toUpperCase()+id.slice(1));if(el)el.value=st.profile[id]});$('variantSummary').textContent=`当前动作版本：${meta('squat').name} · ${meta('push').name} · ${meta('row').name} · ${meta('pull').name}`}
function render(){syncCalibration();renderHistory();const calibrated=!!st.profile.calibrated;$('calibration').classList.toggle('hidden',calibrated);$('todayCard').classList.toggle('hidden',!calibrated);$('settingsCard').classList.toggle('hidden',!calibrated);$('dateText').textContent=fmtDate();$('voice').checked=st.voice;if(!calibrated){$('coach').style.display='none';$('rest').classList.remove('show');$('finish').classList.remove('show');$('dayType').textContent='待校准';$('app').classList.remove('training');save();return}renderPlan();$('elapsedTag').textContent='已用 '+fmtElapsed();$('finishEarly').classList.toggle('hidden',mode!=='work');$('rest').classList.toggle('show',mode==='rest');$('coach').style.display=(mode==='rest'||mode==='done')?'none':'block';$('finish').classList.toggle('show',mode==='done');if(mode==='ready'||mode==='warm-paused'){$('phase').textContent=mode==='warm-paused'?'热身已暂停':'准备';$('name').textContent='2分钟热身';$('rightLabel').textContent='剩余';$('rightValue').textContent=warm;$('goalMain').textContent='轻松活动身体';$('cue').textContent='原地走、肩绕环、徒手深蹲和髋铰链练习。热身不需要做到累。';$('setTag').textContent='热身';$('loadTag').textContent='无需负重';$('variantTag').textContent='动作校准已生效';$('bar').style.width=(1-warm/120)*100+'%';$('setButtons').style.display='none';$('actions').style.display='grid';$('start').textContent=mode==='warm-paused'?'继续':'开始训练';$('app').classList.remove('training')}else if(mode==='warm'){$('phase').textContent='热身';$('name').textContent='2分钟热身';$('rightLabel').textContent='剩余';$('rightValue').textContent=warm;$('goalMain').textContent='轻松活动身体';$('cue').textContent='原地走、肩绕环、徒手深蹲和髋铰链练习。热身不需要做到累。';$('setTag').textContent='热身';$('loadTag').textContent='无需负重';$('variantTag').textContent='动作校准已生效';$('bar').style.width=(1-warm/120)*100+'%';$('setButtons').style.display='none';$('actions').style.display='grid';$('start').textContent='暂停';$('app').classList.add('training')}else if(mode==='work'){let x=plan.arr[pos],e=meta(x.id),p=prescribed(x.id);$('phase').textContent=`${plan.type} · 第${pos+1}/${plan.arr.length}组`;$('name').textContent=e.name;$('rightLabel').textContent=e.type==='time'?'目标':'次数';$('rightValue').textContent=p.value;$('goalMain').textContent=`${loadText(x.id)} × ${p.text}`;$('cue').textContent=e.cue;$('setTag').textContent=`第${x.set}/${x.total}组`;$('loadTag').textContent=loadText(x.id);$('variantTag').textContent=e.name;$('bar').style.width=(pos/plan.arr.length*100)+'%';$('setButtons').style.display='grid';$('actions').style.display='none';$('app').classList.add('training')}persist()}
function activeClock(){if(lastTick){let now=Date.now();sessionMs+=Math.max(0,now-lastTick);lastTick=now;if(sessionMs>=MAX_MS){sessionMs=MAX_MS;finishSession('cap');return false}}return true}
function startClock(){lastTick=Date.now()}
function stopClock(){if(lastTick){sessionMs+=Math.max(0,Date.now()-lastTick);lastTick=0}}
function runTimer(kind){clearTimer();startClock();deadline=Date.now()+(kind==='warm'?warm:restSec)*1000;timer=setInterval(()=>{if(!activeClock())return;let left=Math.max(0,Math.ceil((deadline-Date.now())/1000));if(kind==='warm'){warm=left;$('rightValue').textContent=warm;$('bar').style.width=(1-warm/120)*100+'%';if(left<=0){clearTimer();pos=0;mode='work';speak('热身完成。'+meta(plan.arr[0].id).name+'，'+prescribed(plan.arr[0].id).text);render();startWorkClock()}}else{restSec=left;$('restNum').textContent=restSec;$('elapsedTag').textContent='已用 '+fmtElapsed();if(left<=0)endRest()}persist()},250)}
function clearTimer(stop=true){if(timer){clearInterval(timer);timer=null}if(stop)stopClock()}
function startOrPauseWarm(){if(!st.profile.calibrated)return;if(mode==='ready'||mode==='warm-paused'){mode='warm';runTimer('warm');speak('开始热身。');render()}else if(mode==='warm'){clearTimer();mode='warm-paused';render()}}
function startWorkClock(){clearTimer();startClock();timer=setInterval(()=>{if(mode!=='work'){clearTimer();return}if(!activeClock())return;$('elapsedTag').textContent='已用 '+fmtElapsed();persist()},1000)}
function complete(result){if(mode!=='work')return;clearTimer();plan.arr[pos].result=result;if(pos>=plan.arr.length-1){finishSession('complete');return}let e=meta(plan.arr[pos].id);restSec=e.rest;mode='rest';$('restNum').textContent=restSec;$('nextText').textContent=`下一组：${meta(plan.arr[pos+1].id).name} · ${prescribed(plan.arr[pos+1].id).text}`;render();runTimer('rest')}
function endRest(){clearTimer();pos++;if(pos>=plan.arr.length){finishSession('complete');return}mode='work';speak(meta(plan.arr[pos].id).name+'，'+prescribed(plan.arr[pos].id).text);render();startWorkClock()}
function finishSession(reason){if(sessionFinished)return;clearTimer();sessionFinished=true;let done=plan.arr.filter(x=>x.result!==null).length,partial=done<plan.arr.length||reason!=='complete',hits=plan.arr.filter(x=>x.result==='hit').length,misses=plan.arr.filter(x=>x.result==='miss').length,skips=plan.arr.filter(x=>x.result==='skip').length;mode='done';let entry={date:dateKey(),type:plan.type,planKey:plan.planKey,partial,rating:null,reason,done,total:plan.arr.length,hits,misses,skips,results:plan.arr.map(x=>({id:x.id,result:x.result,variant:st.profile[x.id]||null}))};st.history=st.history.filter(x=>x.date!==dateKey());st.history.push(entry);st.history=st.history.slice(-180);st.active=null;save();$('finishText').textContent=reason==='cap'?'已经达到30分钟上限，今天到这里。剩余内容不再继续。':partial?'今天提前结束也算完成。长期坚持比偶尔硬撑更重要。':'今天整体感觉如何？系统会据此安排下一次。';$('finishMeta').textContent=`完成 ${done}/${plan.arr.length} 组 · 用时 ${fmtElapsed()}`;$('coach').style.display='none';$('rest').classList.remove('show');$('finish').classList.add('show');$('app').classList.remove('training');renderHistory();speak(reason==='cap'?'已经达到三十分钟。今天训练结束。':'训练完成。今天的力量已经存入。')}
function exerciseResults(id){return plan.arr.filter(x=>x.id===id).map(x=>x.result).filter(Boolean)}
function moveVariant(id,dir){let ladder=LADDERS[id];if(!ladder)return null;let cur=st.profile[id],i=ladder.indexOf(cur),j=i+dir;if(i<0||j<0||j>=ladder.length)return null;st.profile[id]=ladder[j];delete st.targets[id];return meta(id).name}
function applyProgress(rate){let advice=[],ids=[...new Set(plan.arr.map(x=>x.id))];ids.forEach(id=>{let e=meta(id),t=target(id),r=exerciseResults(id),hits=r.filter(x=>x==='hit').length,miss=r.filter(x=>x==='miss').length,skips=r.filter(x=>x==='skip').length,allHit=r.length>0&&hits===r.length&&!miss&&!skips;if(plan.light||plan.recovery){advice.push(`${e.name}：恢复/轻量日不推进难度`);return}if(e.type==='reps'){if(allHit&&rate!=='hard'){t.misses=0;t.success=(t.success||0)+1;let needed=rate==='easy'?1:2;if(t.success>=needed){if((t.reps||e.min)<e.max){t.reps=(t.reps||e.min)+1;t.success=0;advice.push(`${e.name}：下次目标 +1次`)}else{let upgraded=moveVariant(id,1);if(upgraded)advice.push(`${e.name}：已稳定达标，下次自动升级为${upgraded}`);else if(e.load&&Number(st.loads[e.load]||0)>0){st.loads[e.load]=Math.round((Number(st.loads[e.load])+e.inc)*2)/2;t.reps=e.min;t.success=0;advice.push(`${e.name}：达到次数上限，下次小幅加重`)}else{t.success=0;advice.push(`${e.name}：当前版本已稳定达标，先保持；有合适器械时再增加阻力`)}}}else advice.push(`${e.name}：再稳定一次，再升级`)}else if(miss>0){t.success=0;t.misses=(t.misses||0)+1;if(t.misses>=2){if((t.reps||e.min)>e.min){t.reps--;t.misses=0;advice.push(`${e.name}：连续两次未达标，下次目标 -1次`)}else{let downgraded=moveVariant(id,-1);if(downgraded)advice.push(`${e.name}：连续两次在最低目标仍未达标，下次自动调整为${downgraded}`);else{t.misses=0;advice.push(`${e.name}：保持最低目标，不继续加量`)}}}else advice.push(`${e.name}：先保持当前目标，不急着降级`)}else if(rate==='hard'){t.success=0;advice.push(`${e.name}：本次偏吃力，下次保持，不加量`)}else if(skips>0)advice.push(`${e.name}：跳过不算失败，下次保持`)}else{if(allHit&&rate!=='hard'){t.success=(t.success||0)+1;let sec=t.seconds||e.seconds;if(t.success>=2){if(sec<e.maxSeconds){t.seconds=Math.min(e.maxSeconds,sec+5);t.success=0;advice.push(`${e.name}：下次 +5秒`)}else if(Number(st.loads[e.load]||0)>0){st.loads[e.load]=Math.round((Number(st.loads[e.load])+e.inc)*2)/2;t.seconds=e.seconds;t.success=0;advice.push(`${e.name}：时间达标，下次每手小幅加重`)}else{t.success=0;advice.push(`${e.name}：时间已达标，可开始增加负重`)}}else advice.push(`${e.name}：再稳定一次，再升级`)}else if(miss>0||rate==='hard'){t.success=0;advice.push(`${e.name}：下次保持当前目标`)}else if(skips>0)advice.push(`${e.name}：跳过不算失败，下次保持`)}});let h=st.history[st.history.length-1];if(h&&h.date===dateKey())h.rating=rate;save();$('nextAdvice').style.display='block';$('nextAdvice').textContent='下次建议：'+advice.slice(0,4).join('；')+'。';syncInputs();syncCalibration();renderHistory()}
function reset(){clearTimer();sessionFinished=false;st.active=null;plan=buildPlan();pos=-1;mode='ready';warm=120;restSec=0;sessionMs=0;lastTick=0;$('finish').classList.remove('show');$('nextAdvice').style.display='none';render()}
function syncInputs(){['sq','rdl','rowLoad','carry'].forEach(id=>{$(id).value=st.loads[id]||''})}
function saveCalibration(){let next={squat:$('calSquat').value,push:$('calPush').value,pull:$('calPull').value,row:$('calRow').value};['squat','push','pull','row'].forEach(id=>{if(st.profile[id]!==next[id])delete st.targets[id];st.profile[id]=next[id]});st.profile.calibrated=true;st.active=null;clearTimer();sessionFinished=false;plan=buildPlan();pos=-1;mode='ready';warm=120;restSec=0;sessionMs=0;lastTick=0;save();render();speak('动作校准完成。今天的训练已经准备好。')}
function recalibrate(){if(mode==='warm'||mode==='work'||mode==='rest')return;st.profile.calibrated=false;st.active=null;save();render()}
function resumeIfNeeded(){if(mode==='work')startWorkClock();else if(mode==='rest'){$('restNum').textContent=restSec;$('nextText').textContent=`下一组：${meta(plan.arr[Math.min(pos+1,plan.arr.length-1)].id).name} · ${prescribed(plan.arr[Math.min(pos+1,plan.arr.length-1)].id).text}`;runTimer('rest')}else render()}
$('start').onclick=startOrPauseWarm;$('reset').onclick=reset;$('hit').onclick=()=>complete('hit');$('miss').onclick=()=>complete('miss');$('skip').onclick=()=>complete('skip');$('endRest').onclick=endRest;$('finishEarly').onclick=()=>finishSession('early');$('finishEarlyRest').onclick=()=>finishSession('early');$('voice').onchange=e=>{st.voice=e.target.checked;save()};$('saveCalibration').onclick=saveCalibration;$('recalibrate').onclick=recalibrate;['sq','rdl','rowLoad','carry'].forEach(id=>{$(id).onchange=e=>{st.loads[id]=Math.max(0,Number(e.target.value||0));save();renderPlan()}});document.querySelectorAll('.rate').forEach(b=>b.onclick=()=>applyProgress(b.dataset.rate));
document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenAt=Date.now();if(mode==='warm'||mode==='rest'||mode==='work'){clearTimer();persist()}}else if(hiddenAt){let gap=Date.now()-hiddenAt;hiddenAt=0;if(gap>BG_PAUSE_MS){if(mode==='warm')mode='warm-paused';if(mode==='rest')$('nextText').textContent='离开时间较久，休息计时已暂停。点击“提前开始”继续。';render();if(mode==='work')startWorkClock()}else{if(mode==='warm')runTimer('warm');else if(mode==='rest')runTimer('rest');else if(mode==='work')startWorkClock()}}});
window.addEventListener('beforeunload',()=>{clearTimer();persist()});
syncInputs();render();if(st.profile.calibrated&&(mode==='work'||mode==='rest'))resumeIfNeeded();
})();
